export const SPOTIFY_CLIENT_ID = process.env.REACT_APP_SPOTIFY_CLIENT_ID;
export const SPOTIFY_CLIENT_SECRET =
  process.env.REACT_APP_SPOTIFY_CLIENT_SECRET;
export const SPOTIFY_REDIRECT_URL = process.env.REACT_APP_SPOTIFY_REDIRECT_URL;
